In [5]:
# 문자열 처리
import pandas as pd

df = pd.DataFrame({
    'A': ["데이터 분석", "머신러닝 분류", "카이제곱 검정"],
    'B': [10, 20, 30],
    'C': ['ab cd', 'AB CD', 'ab cd ']
})
# print(df)

# str 속성 - 문자 추출
# df['A추출'] = df['A'].str[:4]
df['A추출'] = df['A'].str[-2:]
print(df)

# replace() - 요소 단위, str.replace()는 특정 문자열 
# df['A'] = df['A'].replace("머신러닝 분류", "머신러닝 회귀")
df['A'] = df['A'].str.replace("분류", "회귀")
# print(df)

# replace() - 숫자 변경 가능, str.replace()는 숫자 변경 불가 
df['B'] = df['B'].replace(20, 40)
# df['B'] = df['B'].str.replace(20, 40)
print(df)

print(df['A'].str.split()) #공백 문자로 분리 
df['A'].str.split()[0]
df['D'] = df['A'].str.split().str[0]
print(df)

# # contains() - 특정 문자열 포함
df["검정포함여부"] = df['A'].str.contains("검정")
print(df)

# # 소문자로 변경 
df['C'] = df['C'].str.lower()
print(df['C'])

# # 공백 제거 
df['C'] = df['C'].str.strip()
print(df['C'])

         A   B       C A추출
0   데이터 분석  10   ab cd  분석
1  머신러닝 분류  20   AB CD  분류
2  카이제곱 검정  30  ab cd   검정
         A   B       C A추출
0   데이터 분석  10   ab cd  분석
1  머신러닝 회귀  40   AB CD  분류
2  카이제곱 검정  30  ab cd   검정
0     [데이터, 분석]
1    [머신러닝, 회귀]
2    [카이제곱, 검정]
Name: A, dtype: object
         A   B       C A추출     D
0   데이터 분석  10   ab cd  분석   데이터
1  머신러닝 회귀  40   AB CD  분류  머신러닝
2  카이제곱 검정  30  ab cd   검정  카이제곱
         A   B       C A추출     D  검정포함여부
0   데이터 분석  10   ab cd  분석   데이터   False
1  머신러닝 회귀  40   AB CD  분류  머신러닝   False
2  카이제곱 검정  30  ab cd   검정  카이제곱    True
0     ab cd
1     ab cd
2    ab cd
Name: C, dtype: object
0    ab cd
1    ab cd
2    ab cd
Name: C, dtype: object

In [12]:
# 시계열 데이터
data = {
    "날짜": ["2025-3-1", "2025-3-2", "2025-3-3"],
    "날짜와시간": ["2025-3-1 10:20:50", 
            "2025-3-2 11:25:10", "2025-3-3 12:40:15"],
}

df = pd.DataFrame(data)
df.info()

# 자료형 변환(parsing) : object -> to_datetime()
df["날짜"] = pd.to_datetime(df["날짜"])
df["날짜와시간"] = pd.to_datetime(df["날짜와시간"])
df
df.info()

# 년, 월, 일 추출 - dt 접근자 사용 
# df["연도"] = df["날짜"].dt.year
# df["월"] = df["날짜"].dt.month
# df["일"] = df["날짜"].dt.day

# 년, 월, 일, 시, 분, 초 추출
df["연도"] = df["날짜와시간"].dt.year
df["월"] = df["날짜와시간"].dt.month
df["일"] = df["날짜와시간"].dt.day
df["시"] = df["날짜와시간"].dt.hour
df["분"] = df["날짜와시간"].dt.minute
df["초"] = df["날짜와시간"].dt.second
df

# 요일(0-월, 1-화, 2-수, 3-목, 4-금, 5-토, 6-일)
weeks = df["날짜와시간"].dt.dayofweek
print(type(weeks)) # 시리즈
print(list(weeks)) # 리스트로 변환 
for week in weeks:
    if week == 0:
        print("월")
    if week == 1:
        print("화")
    if week == 2:
        print("수")
    if week == 3:
        print("목")
    if week == 4:
        print("금")
    if week == 5:
        print("토")
    if week == 6:
        print("일")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      3 non-null      object
 1   날짜와시간   3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      3 non-null      datetime64[ns]
 1   날짜와시간   3 non-null      datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 180.0 bytes
<class 'pandas.core.series.Series'>
[5, 6, 0]
토
일
월

In [19]:
import pandas as pd

data = {
    "출발시간": ["2025-3-10 10:20:50"],
    "도착시간": ["2025-3-10 10:30:10"]
}

df = pd.DataFrame(data)

df["출발시간"] = pd.to_datetime(df["출발시간"])
df["도착시간"] = pd.to_datetime(df["도착시간"])

df.info()

# df["시간차이(분)"] = (df["도착시간"] - df["출발시간"])
df["시간차이(분)"] = (df["도착시간"] - df["출발시간"]).dt.total_seconds() / 60
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   출발시간    1 non-null      datetime64[ns]
 1   도착시간    1 non-null      datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 148.0 bytes

                 출발시간                도착시간   시간차이(분)
0 2025-03-10 10:20:50 2025-03-10 10:30:10  9.333333

In [65]:
# 요일(0-월, 1-화, 2-수, 3-목, 4-금, 5-토, 6-일)
weeks = df["날짜와시간"].dt.dayofweek
print(type(weeks)) # 시리즈
print(list(weeks)) # 리스트로 변환 
# print(weeks[0])
weeks2 = []
for week in weeks:
    if week == 0:
        weeks2.append("월")
    if week == 1:
        weeks2.append("화")
    if week == 2:
        weeks2.append("수")
    if week == 3:
        weeks2.append("목")
    if week == 4:
        weeks2.append("금")
    if week == 5:
        weeks2.append("토")
    if week == 6:
        weeks2.append("일")
print(weeks2)
df["요일"] = weeks2
df

<class 'pandas.core.series.Series'>
[5, 6, 0]
['토', '일', '월']

          날짜               날짜와시간    연도  월  일   시   분   초 요일
0 2025-03-01 2025-03-01 10:20:50  2025  3  1  10  20  50  토
1 2025-03-02 2025-03-02 11:25:10  2025  3  2  11  25  10  일
2 2025-03-03 2025-03-03 12:40:15  2025  3  3  12  40  15  월

In [9]:
# 데이터 프레임 합치기
import pandas as pd

# 단순 병합 - concat()
lunch = pd.DataFrame({
    'menu': ["피자", "치킨", "햄버거"],
    'price': [20000, 15000, 8000]
})
lunch

drink = pd.DataFrame({
    'menu': ["주스", "커피", "콜라"],
    'price': [3000, 4000, 2000]
})
drink

# 위 + 아래 
# ignore_index -> 기존 인덱스를 새롭게 변경, axis=0 생략 가능 
# pd.concat?
# full_menu = pd.concat([lunch, drink], ignore_index=True, axis=0)

# 왼쪽 + 오른쪽 
full_menu = pd.concat([lunch, drink], axis=1)
full_menu

  menu  price menu  price
0   피자  20000   주스   3000
1   치킨  15000   커피   4000
2  햄버거   8000   콜라   2000

In [84]:
# 키(Key) 기준 병합 - merge()

가격 = pd.DataFrame({
    'menu': ["피자", "치킨", "햄버거"],
    'price': [20000, 15000, 8000]
})
가격

주문수량 = pd.DataFrame({
    'menu': ["피자", "치킨", "햄버거"],
    'quantity': [2, 3, 5]
})
주문수량

# pd.merge?
메뉴정보 = pd.merge(가격, 주문수량, on="menu")