In [5]:
import pandas as pd
import numpy as np #수치 계산 라이브러리

# 데이터프레임 만들기
df = pd.DataFrame({
    'A': [1, None, 3],
    'B': [4, 5, None]
})
df

# 칼럼 추가
df['C'] = np.nan
df

# csv 파일로 변환
df.to_csv("./datas/data_nan.csv", index=False)

     A    B   C
0  1.0  4.0 NaN
1  NaN  5.0 NaN
2  3.0  NaN NaN

In [13]:
import pandas as pd

# csv 파일 읽기
df_nan = pd.read_csv("./datas/data_nan.csv")
df_nan

# 데이터 탐색
# df_nan.info()
# df_nan.isna().sum()

# 결측치가 있는 1행 삭제
# inplace=True (실행중 즉시 삭제)
df_nan.drop(1, axis=0, inplace=True)
df_nan

# 결측치가 있는 열 삭제
df_nan = df_nan.drop('C', axis=1)
df_nan

     A    B
0  1.0  4.0
2  3.0  NaN

In [16]:
# 결측치 대체

import pandas as pd

data = {
    "메뉴": ["김밥", "비빔밥", "자장면", "우동", None, "자장면", "김밥"],
    "가격": [3000, 7000, 5500, None, 3500, 6000, 4000],
    "분류": ["한식", "한식", "중식", "일식", "한식", "중식", "한식"]
}

food = pd.DataFrame(data)
food

food.info()
food.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      6 non-null      object
 1   가격      6 non-null      float64
 2   분류      7 non-null      object
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

메뉴    1
가격    1
분류    0
dtype: int64

In [20]:
# 결측치 대체
# 수치형
median = food["가격"].median()
median

food["가격"] = food["가격"].fillna(median)
food

# 문자형
frequency = food["메뉴"].mode()[0]
food["메뉴"] = food["메뉴"].fillna(frequency)
food

    메뉴      가격  분류
0   김밥  3000.0  한식
1  비빔밥  7000.0  한식
2  자장면  5500.0  중식
3   우동  4750.0  일식
4   김밥  3500.0  한식
5  자장면  6000.0  중식
6   김밥  4000.0  한식